package com.uzair.kptehsilmunicipaladministrationservices.Models;

import com.uzair.kptehsilmunicipaladministrationservices.Presenters.BirthCertificatePresenter;

public class BirthCertificatePresenterImplementer implements BirthCertificatePresenter
{

}
